# (C) 2026: Hans Georg Schaathun <georg@schaathun.net> 
[simulator]
configs = [ "raysie" ]
size = 24000
nterms = 4
imagesize = 512
cropsize = 256

[lens]
# Einstein radius 0.04" .. 3.0"
einstein-min = 2.5
einstein-max = 75
# orientation and ellipseratio are used for SIE lenses
orientation-min = 0
orientation-max = 180
ellipseratio-min = 0.6
ellipseratio-max = 0.9

[source]
mode = "SersicSphere"
n_sersic-min = 1
n_sersic-max = 5
luminosity-min = 10
luminosity-min = 20
luminosity-lambda = 2.0
sigma-min = 1.25
sigma-max = 20
position = "polar"

[position]
# (phi,r) is the source position in polar co-ordinates, angle in degrees
phi-min = 0
phi-max = 360
r-min = 1
r-max = 75

