[simulator]
model="Raytrace"
cropsize=256

[lens]
mode="SIE"
einsteinradius=46
ellipseratio=0.34
orientation=107

[source]
mode="SersicSphere"
sigma=20
sigma2=10
theta=45
position="cartesian"
n_sersic=4
luminosity=50

[position]
x=11.01
y=0.31

